apiVersion: v1
kind: ConfigMap
metadata:
  name: eventservice-config
  namespace: event-booking
data:
  PORT: "3002"
  GRPC_PORT: "50051"
  MONGODB_HOSTNAME: "mongodb"
  MONGODB_DBNAME: "eventdb"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
