apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: event-booking
data:
  PORT: "3000"
  JWT_SECRET: "exam-demo-jwt-secret"
  FAKE_USER_USERNAME: "admin"
  FAKE_USER_PASSWORD: "password"
  FRONTEND_PATH: "./frontend"