apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-config
  namespace: event-booking
data:
  PORT: "3003"
  GRPC_PORT: "50051"
  MONGODB_HOSTNAME: "mongodb"
  MONGODB_DBNAME: "bookingdb"
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  EVENT_SERVICE_GRPC_URL: "event-service:50051"
