apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: event-booking
spec:
  selector:
    app: bookingservice
  ports:
    - name: http
      port: 3003
      targetPort: 3003
  type: ClusterIP