apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventservice-deployment
  namespace: event-booking
  labels:
    app: eventservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
    spec:
      imagePullSecrets:
        - name: my-registry-credentials
      containers:
        - name: eventservice
          image: registry.gitlab.au.dk/swwao/f2026/exam-projects/group-1/event-booking/event-service:v1.8.6
          ports:
            - containerPort: 3002
              name: http
            - containerPort: 50051
              name: grpc
          envFrom:
            - configMapRef:
                name: eventservice-config
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGODB_URI
              value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/eventdb?authSource=admin"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "250m"
