apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuYXUuZGsiOnsidXNlcm5hbWUiOiJHaXRMYWIgV29ya2Zsb3cgRXh0ZW5zaW9uIiwicGFzc3dvcmQiOiJnbHBhdC1aWkh2bE0zNTg0NU1pRDB6TEtpZkZtODZNUXAxT2pRNVl3ay4wMS4wejAzZXVydGYiLCJlbWFpbCI6IjIwMjIwNTY5M0Bwb3N0LmF1LmRrIiwiYXV0aCI6IlIybDBUR0ZpSUZkdmNtdG1iRzkzSUVWNGRHVnVjMmx2YmpwbmJIQmhkQzFhV2toMmJFMHpOVGcwTlUxcFJEQjZURXRwWmtadE9EWk5VWEF4VDJwUk5WbDNheTR3TVM0d2VqQXpaWFZ5ZEdZPSJ9fX0=
metadata:
  name: my-registry-credentials
  namespace: event-booking
type: kubernetes.io/dockerconfigjson