apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: event-booking
data:
  PORT: "3001"
  MONGODB_HOSTNAME: "mongodb"
  MONGODB_DBNAME: "userdb"
  RABBITMQ_URL: "amqp://rabbitmq:5672"